adminUser:
  password: vault:jx-aps-whimseylily/adminUser:password
  username: admin
dashboardAuthID: vault:jx-aps-whimseylily:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:jx-aps-whimseylily:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:jx-aps-whimseylily/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:jx-aps-whimseylily/prow:hmacToken
